version: '3.8'

services:

  backend:
    build: ./password_wallet
    container_name: backend_wallet
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./password_wallet:/usr/src/password_wallet
    ports:
      - 8000:8000
    env_file:
      - ./password_wallet/.env.dev
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    container_name: db_wallet
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_wallet
    environment:
      - PGADMIN_DEFAULT_EMAIL=${EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PASSWORD}
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
volumes:
  postgres_data: