# Generated by Django 4.1.2 on 2022-12-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_password_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unsuccessful_time_login',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
