# Generated by Django 4.1.2 on 2022-10-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_password_nonce_password_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='nonce',
            field=models.BinaryField(blank=True, default=b'', editable=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='password',
            name='password_to_wallet',
            field=models.BinaryField(editable=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='password',
            name='tag',
            field=models.BinaryField(blank=True, default=b'', editable=True, max_length=256),
        ),
    ]
