# Generated by Django 4.1.2 on 2022-10-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_password_nonce_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password',
            name='nonce',
        ),
        migrations.RemoveField(
            model_name='password',
            name='tag',
        ),
        migrations.AddField(
            model_name='password',
            name='secret_key',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
