# Generated by Django 4.1.4 on 2023-01-06 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0006_remove_password_secret_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.password')),
                ('share_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_by', to=settings.AUTH_USER_MODEL)),
                ('share_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
